exclude: >
  (?x)^(
      .*/snap_.*.py
      .*/.*_pb2.py
  )$
repos:
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
    - id: reorder-python-imports
      args: ['--application-directories=.:graphene_tornado']
      language_version: python3

-   repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
    - id: black
      args: [--safe, --verbose]
      language_version: python3
